# Generated by Django 2.2 on 2019-04-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
