# Generated by Django 2.2 on 2019-11-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='featured_image_copyrights_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='featured_image_copyrights_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
