# Generated by Django 2.2 on 2019-04-15 08:42

import cartoview.base_resource.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_resource', '0003_auto_20190414_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='abstract',
            field=models.TextField(blank=True, default='No Abstract Provided', null=True),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to=cartoview.base_resource.models.thumbnail_path),
        ),
    ]
