# Generated by Django 2.2 on 2019-04-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_resource', '0004_auto_20190415_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basemodel',
            old_name='feature_image',
            new_name='featured_image',
        ),
    ]
