# Generated by Django 2.2 on 2019-04-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_resource', '0005_auto_20190415_1203'),
        ('base_resource', '0005_auto_20190415_1231'),
    ]

    operations = [
    ]
