# Generated by Django 2.2 on 2019-04-15 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_resource', '0006_merge_20190415_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedresource',
            name='content_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_items', to='base_resource.BaseModel'),
        ),
    ]
