# Generated by Django 2.2 on 2019-04-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='selected_template',
            field=models.CharField(choices=[('cms/home_page_default.html', 'Default Template')], default='cms/home_page_default.html', max_length=255),
        ),
    ]
