# Generated by Django 2.2 on 2019-07-23 07:00

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('cms', '0002_sitesettings_partners_logos'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('selected_template', models.CharField(choices=[('cms/static_page/static_page_default.html', 'Default Template')], default='cms/static_page/static_page_default.html', max_length=255)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Static Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
