# Generated by Django 2.1.8 on 2019-04-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20190414_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
