# Generated by Django 2.2 on 2019-08-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_languageredirectionpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_text_ar',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Logo text (AR)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_text',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Logo text (EN)'),
        ),
    ]
