# Generated by Django 2.2 on 2019-10-21 08:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20190828_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='partners_logos',
            field=wagtail.core.fields.StreamField([('partners', wagtail.core.blocks.StructBlock([('image_items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('link', wagtail.core.blocks.CharBlock(label='link', max_length=200, required=False))]), label='Image'))]))], blank=True, null=True),
        ),
    ]
