sudo: required
dist: focal
language: python
cache:
  directories:
    - "$HOME/.cache/pip"
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-12-postgis-3
      - libevent-dev
services:
  - postgresql
python:
  - '3.10'
env:
  global:
    - CARTOVIEW_TEST=True
    - DATABASE_URL=postgis://cartoview:docker@localhost:5432/cartoview
    - DATASTORE_DATABASE_URL=postgis://cartoview:cartoview@localhost:5432/cartoview_data
virtualenv:
  system_site_packages: false
branches:
  except:
    - 2.6.x_compatible
    - 1.4.4-(mapground)
    - mapground(1.8)
    - exchange-1.4.x
before_install:
  - sudo apt-get autoremove sqlite3;
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf;
  - sudo sed -i 's/peer/trust/' /etc/postgresql/12/main/pg_hba.conf;
  - sudo pg_ctlcluster 12 main restart;
install:
  - sudo apt-get -qq -y update
  - sudo apt-get install -y gcc gettext python3-pip libpq-dev sqlite3 spatialite-bin libsqlite3-mod-spatialite libsqlite3-dev git gdal-bin lsof
    psmisc
  - sudo apt-get install -y python3-gdal python-lxml
  - sudo apt-get install -y python3-virtualenv python-pil python3-pil python3-lxml python3-pyproj python3-shapely python3-httplib2 python3-httplib2
  - sudo apt-get install -y python3-dev libgdal-dev libgeoip-dev libxml2
    libxml2-dev libxslt-dev git default-jdk
  - sudo apt-get install -y python-dev libxml2 libxml2-dev libxslt1-dev zlib1g-dev libjpeg-dev
    libpq-dev libgdal-dev git default-jdk
  - sudo apt-get install -y libmemcached-dev libsasl2-dev zlib1g-dev python-pylibmc
    python-setuptools
  - sudo apt-get install -y curl build-essential build-essential python-dev libffi-dev
    libssl-dev
  - sudo apt-get update
  - sudo apt install -y openjdk-8-jre openjdk-8-jdk ant maven;
  - sudo update-java-alternatives --set java-1.8.0-openjdk-amd64;
  - export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::");
  - export PATH=$JAVA_HOME'bin/java':$PATH;
  - pip install celery
  - pip install pygdal==`gdal-config --version`.*
  - pip install tqdm
  - pip install -e . --upgrade
  - pip install timeout-decorator
  - paver setup_geoserver
  - paver start_geoserver
  - pip install coveralls
before_script:
  - psql -U postgres -c "create extension postgis"
  - chmod +x scripts/database/setup.sh
  - scripts/database/setup.sh
script:
  - flake8
  - paver run_cartoview_test
after_success:
- coveralls
deploy:
  provider: pypi
  user: cartologic
  password:
    secure: I55fbMkUDNnPVRejHETev9viO7nY9bD+wXzPk0MoLKhx5KceyAPYXnznVYMid7FVzBZzP6pLT9k8lZTC+Xv6ZET8GK/cgwPd+i3n8upk2PKAzjUCxutXrxTPHCKyd9HHz051Wt/0vJvhKsw37E/WPFach007gGjF2J/diGdEFtvrKYE+ixYd6wu6VevKGtCce4Wt2HY7fZ7rfhHbEdX/k2hOzrBiD5fwHp+GJdcczGpzKdtdKvdhkUEDsBs6y1hUgGbCF9i3TiagEA3/Md/bG4mU4P+B1oAkdXue9TVLOEMXD1rpdR/EMm0FwMsnZWtaYTTkvEmPrYBhLcN7NlM0/VaSJ6ejbD9nk+37uE2h7S/xKsmCezzYEDeDAXmMa3WDQQrSYLuypN8DgxFhYiac+qYIBSMUOyI+EJXSpJ9iHaseofvF+32DAm6U6P2kEpda619HuEEF++JxthVJ01hAaQDoezEisirXT0pWKEQcSbTeI5hTP0kCxxlpqgg1CNmSvSXQbTMs9FyOTIJBHkhj4rLnTI+UPv99ig0CFzQO2HbBa+4kiWl4LpGZrNd9ei1wlxpSScJsQbu3bYUfpRqY7AiPkYkaIb1jCCWwxS/AgBX7YbT4os/E+zBQGvldQncCXhtVYA6+cpGzZM29lKUHy4KMNsiB744a48AGGUv04cg=
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_TAG =~ ^v([0-9]+\.?){2,3}(b[0-9]+|rc[0-9]+){0,1}
notifications:
  email:
    - ahmednosman@cartologic.com
    - ahmedNourElDeen@cartologic.com
