version: "3"
services:
  postgis:
    image: kartoza/postgis:13
    volumes:
      - postgis-data:/var/lib/postgresql
      # - dbbackups:/backups
    env_file:
      - ./env/postgis.env
    expose:
      - "5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
    networks:
      -cartoview-internal:
  elasticsearch:
    image: elasticsearch:5.6.12-alpine
    restart: unless-stopped
    stdin_open: true
    tty: true
    expose:
      - "9300"
      - "9200"
    networks:
      -cartoview-internal:
  rabbitmq:
    image: rabbitmq:latest
    restart: unless-stopped
    expose:
      - "5672"
      - "15672"
    networks:
      -cartoview-internal:
  data-dir-conf:
    image: geonode/geoserver_data:2.19.x
    restart: on-failure
    container_name: gsconf4cartoview
    command: /bin/true
    volumes:
      - geoserver-dir:/geoserver_data/data
  geoserver:
    image: geonode/geoserver:2.19.x
    depends_on:
      - postgis
      - data-dir-conf
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - geoserver-dir:/geoserver_data/data
    env_file:
      - ./env/tomcat.env
    networks:
      -cartoview-external:
        ipv4_address: 10.5.0.2
      -cartoview-internal:
  cartoview:
    image: cartologic/cartoview:latest
    container_name: cartoview_django
    command: bash -c "python manage.py cherry_server"
    restart: unless-stopped
    hostname: cartoview
    depends_on:
      - postgis
      - geoserver
    env_file:
      - ./env/django.env
    volumes:
      - "./:/usr/src/carto_app/cartoview"
      - geoserver-dir:/geoserver_data/data
    networks:
      -cartoview-external:
        ipv4_address: 10.5.0.3
      -cartoview-internal:
    expose:
      - "8000"
  celery:
    image: cartologic/cartoview:latest    
    container_name: cartoview_celery
    command: bash -c "celery -A cartoview.celery:app worker -B -E --statedb=./worker.state -s ./celerybeat-schedule --loglevel=INFO --concurrency=10 -n worker1@%h -f /var/log/celery.log"
    restart: unless-stopped
    hostname: celery
    depends_on:
      - postgis
      - rabbitmq
      - geoserver
    stdin_open: true
    env_file:
      - ./env/celery.env
    volumes:
      - "./:/code/"
    networks:
      -cartoview-internal:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./scripts/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static/:/cartoview/static/
      - ./uploaded/:/cartoview/uploaded/
    networks:
      -cartoview-external:
        ipv4_address: 10.5.0.4
      -cartoview-internal:
    ports:
      - "80:80"
networks:
  -cartoview-external:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
  -cartoview-internal:
    internal: true
volumes:
  geoserver-dir:
  postgis-data:
