import os
from setuptools import setup

with open(os.path.join(os.path.dirname(__file__), 'README.md')) as readme:
    README = readme.read()

# allow setup.py to be run from any path
os.chdir(os.path.normpath(os.path.join(os.path.abspath(__file__), os.pardir)))

# Package dependencies
install_requires = [
    'appdirs>=1.4.3',
    'appnope>=0.1.0',
    'asgiref>=2.3.2',
    'asn1crypto>=0.24.0',
    'async-timeout>=3.0.1',
    'attrs>=18.2.0',
    'autobahn>=19.3.3',
    'Automat>=0.7.0',
    'autopep8>=1.4.2',
    'backcall>=0.1.0',
    'beautifulsoup4>=4.6.0',
    'black>=18.9b0',
    'certifi>=2018.10.15',
    'cffi>=1.12.2',
    'channels>=2.1.7',
    'chardet>=3.0.4',
    'Click>=7.0',
    'constantly>=15.1.0',
    'coreapi>=2.3.3',
    'coreschema>=0.0.4',
    'cryptography>=2.6.1',
    'daphne>=2.2.5',
    'decorator>=4.3.2',
    'defusedxml>=0.5.0',
    'Django>=2.2',
    'django-admin>=1.3.2',
    'django-allauth>=0.38.0',
    'django-appconf>=1.0.3',
    'django-cogwheels>=0.2',
    'django-crispy-forms>=1.7.2',
    'django-excel-response2>=2.0.8',
    'django-fernet-fields>=0.5',
    'django-filter>=2.1.0',
    'django-guardian>=1.5.0',
    'django-modelcluster>=4.3',
    'django-redis>=4.10.0',
    'django-rest-swagger>=2.2.0',
    'django-six>=1.0.4',
    'django-taggit>=0.23.0',
    'django-treebeard>=4.3',
    'djangorestframework>=3.9.1',
    'djangorestframework-xml>=1.4.0',
    'djangorestframework-yaml>=1.0.3',
    'draftjs-exporter>=2.1.5',
    'flake8>=3.6.0',
    'future>=0.17.1',
    'gunicorn>=19.9.0',
    'h11>=0.8.1',
    'html5lib>=1.0.1',
    'httptools>=0.0.13',
    'hyperlink>=18.0.0',
    'idna>=2.7',
    'incremental>=17.5.0',
    'ipython>=7.3.0',
    'ipython-genutils>=0.2.0',
    'isort>=4.3.4',
    'itypes>=1.1.0',
    'jedi>=0.13.2',
    'Jinja2>=2.10',
    'Markdown>=3.0.1',
    'MarkupSafe>=1.1.0',
    'mccabe>=0.6.1',
    'oauthlib>=2.1.0',
    'openapi-codec>=1.3.2',
    'OWSLib>=0.17.1',
    'parso>=0.3.4',
    'pexpect>=4.6.0',
    'pickleshare>=0.7.5',
    'Pillow>=5.4.1',
    'portalocker>=1.4.0',
    'prompt-toolkit>=2.0.8',
    'psycopg2-binary>=2.7.7',
    'ptyprocess>=0.6.0',
    'pycodestyle>=2.4.0',
    'pycparser>=2.19',
    'pyflakes>=2.0.0',
    'Pygments>=2.3.1',
    'PyHamcrest>=1.9.0',
    'pyproj>=1.9.6',
    'python-dateutil>=2.8.0',
    'python3-openid>=3.1.0',
    'pytz>=2018.7',
    'PyYAML>=5.1',
    'redis>=3.2.1',
    'requests>=2.20.1',
    'requests-oauthlib>=1.0.0',
    'rest-framework-generic-relations>=1.2.1',
    'screen>=1.0.1',
    'simplejson>=3.16.0',
    'six>=1.12.0',
    'sqlparse>=0.3.0',
    'toml>=0.10.0',
    'traitlets>=4.3.2',
    'Twisted>=18.9.0',
    'txaio>=18.8.1',
    'Unidecode>=1.0.23',
    'uritemplate>=3.0.0',
    'urllib3>=1.24.1',
    'uvicorn>=0.6.1',
    'wagtail>=2.4',
    'wagtailgridder>=0.9.30',
    'wagtailmenus>=2.12',
    'wcwidth>=0.1.7',
    'webencodings>=0.5.1',
    'websockets>=7.0',
    'Willow>=1.1',
    'xlwt>=1.3.0',
    'zope.interface>=4.6.0',
]

# Testing dependencies
testing_extras = [
]

# Documentation dependencies
documentation_extras = [
]

setup(
    name='cartoview_2',
    version='0.0.1',
    packages=['cartoview_2'],
    include_package_data=True,
    license='BSD',
    description='A GIS Web Mapping Application Market. Create, share, and visualize GIS Web Mapping Applications',
    long_description=README,
    url='https://github.com/cartologic/cartoview_2/',
    author='cartologic',
    author_email='cartoview@cartologic.com',
    keywords=['cartoview', 'gis', 'django', 'web mapping', 'geonode', 'application management'],
    classifiers=[
        'Development Status :: 4 - Beta',
        'Environment :: Web Environment',
        'Framework :: Django :: 2.2',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content :: Content Management System',
        'Topic :: Scientific/Engineering',
        'Topic :: Scientific/Engineering :: GIS',
        'Topic :: Software Development',
    ],
    install_requires=install_requires,
    extras_require={
        'testing': testing_extras,
        'docs': documentation_extras
    },
)
