# Generated by Django 2.1.3 on 2019-03-07 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='server',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
