# Generated by Django 2.1.3 on 2019-03-21 14:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='operations',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
