# Generated by Django 2.2 on 2019-05-08 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('ARCGIS_MSL', 'ArcGIS Map Server Layer'), ('ARCGIS_FSL', 'ArcGIS Feature Server Layer'), ('OGC-WMS', 'OGC Web Map Service'), ('OGC-WFS', 'OGC Web Feature Service'), ('GEONODE', 'Geonode'), ('GEOJSON', 'GeoJSON'), ('KML', 'KML'), ('POSTGIS', 'PostGIS')], help_text='Server Type', max_length=15),
        ),
        migrations.AlterField(
            model_name='server',
            name='url',
            field=models.TextField(help_text='Base Server URL', validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'ftp', 'ftps', 'postgis'])]),
        ),
    ]
