# Generated by Django 2.2 on 2019-07-16 09:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('server', 'owner')},
        ),
    ]
