# Generated by Django 2.1.3 on 2019-03-23 22:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_server_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='operations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
