# Generated by Django 2.1.3 on 2019-03-10 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_auto_20190307_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='refresh_interval',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
    ]
