# Generated by Django 2.1.3 on 2019-03-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0007_auto_20190324_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='resources_type',
        ),
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('ESRI', 'ArcGIS Server'), ('OGC-WMS', 'OGC Web Map Service'), ('OGC-WFS', 'OGC Web Feature Service'), ('G', 'Geonode'), ('GEOJSON', 'GeoJSON'), ('KML', 'KML')], help_text='Server Type', max_length=15),
        ),
    ]
