# Generated by Django 2.1.3 on 2019-03-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0008_auto_20190326_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('ARCGIS_MSL', 'ArcGIS Map Server Layer'), ('ARCGIS_FSL', 'ArcGIS Feature Server Layer'), ('OGC-WMS', 'OGC Web Map Service'), ('OGC-WFS', 'OGC Web Feature Service'), ('G', 'Geonode'), ('GEOJSON', 'GeoJSON'), ('KML', 'KML')], help_text='Server Type', max_length=15),
        ),
    ]
