# Generated by Django 2.1.3 on 2019-03-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0009_auto_20190328_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simpleauthconnection',
            options={'permissions': (('use_for_read', 'Allow to use for read operations'), ('use_for_write', 'Allow to use for write operations'))},
        ),
        migrations.AlterModelOptions(
            name='tokenauthconnection',
            options={'permissions': (('use_for_read', 'Allow to use for read operations'), ('use_for_write', 'Allow to use for write operations'))},
        ),
    ]
