# Generated by Django 2.2 on 2019-04-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0010_auto_20190330_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('ARCGIS_MSL', 'ArcGIS Map Server Layer'), ('ARCGIS_FSL', 'ArcGIS Feature Server Layer'), ('OGC-WMS', 'OGC Web Map Service'), ('OGC-WFS', 'OGC Web Feature Service'), ('GEONODE', 'Geonode'), ('GEOJSON', 'GeoJSON'), ('KML', 'KML')], help_text='Server Type', max_length=15),
        ),
    ]
