# Generated by Django 2.2 on 2019-04-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0011_auto_20190410_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='refresh_interval',
        ),
    ]
