# Generated by Django 2.2 on 2019-08-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_map_geonode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='abstract_ar',
            field=models.TextField(blank=True, default='بدون نبذه مختصره', help_text='بدون نبذه مختصره', null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='description_ar',
            field=models.TextField(blank=True, default='بدون وصف', help_text='بدون وصف', null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='title_ar',
            field=models.CharField(default='بدون عنوان', help_text='بدون عنوان', max_length=255),
        ),
    ]
