# Generated by Django 2.1.3 on 2019-03-19 03:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20190319_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='center',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=30, null=True), default=list, size=2),
        ),
    ]
