# Generated by Django 2.2 on 2019-04-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20190414_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='layers',
            field=models.ManyToManyField(blank=True, to='layers.Layer'),
        ),
    ]
