# Generated by Django 2.1.3 on 2019-03-19 03:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20190319_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='render_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
