# Generated by Django 2.1.3 on 2019-03-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20190319_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='center',
            field=models.CharField(default='[0,0]', max_length=150),
        ),
    ]
