# Generated by Django 2.1.3 on 2019-03-19 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20190319_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='enableRotation',
            new_name='enable_rotation',
        ),
    ]
