# Generated by Django 2.1.3 on 2019-03-19 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20190319_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='minZoom',
            new_name='min_zoom',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='zoomFactor',
            new_name='zoom_factor',
        ),
    ]
