# Generated by Django 2.1.3 on 2019-03-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20190319_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
    ]
