# Generated by Django 2.2 on 2019-05-11 18:16

import cartoview.dynamic_models.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[cartoview.dynamic_models.models.field_name_validator])),
                ('created', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModelField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.TextField(choices=[('django.db.models.TextField', 'Text'), ('django.db.models.FloatField', 'Number')])),
                ('name', models.CharField(max_length=255, validators=[cartoview.dynamic_models.models.field_name_validator])),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dynamic_models.Model')),
            ],
        ),
    ]
