# Generated by Django 3.1.7 on 2021-02-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('abstract', models.TextField(blank=True, max_length=2000, null=True)),
                ('config', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
