# Generated by Django 2.2 on 2019-04-30 10:57

from django.db import migrations, models
import wagtail.contrib.table_block.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('values', wagtail.core.fields.StreamField([('table', wagtail.contrib.table_block.blocks.TableBlock())])),
            ],
            options={
                'verbose_name': 'Data Table',
                'verbose_name_plural': 'Data Tables',
            },
        ),
    ]
