# Generated by Django 2.2 on 2019-05-13 11:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatable',
            name='values',
        ),
        migrations.AddField(
            model_name='datatable',
            name='fields',
            field=wagtail.core.fields.StreamField([('field', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('type', wagtail.core.blocks.ChoiceBlock(choices=[('text', 'Text'), ('number', 'Number')]))]))], blank=True, null=True),
        ),
    ]
