# Generated by Django 2.1.3 on 2019-03-07 19:42

import cartoview.layers.validators
import datetime
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0002_auto_20190307_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('bounding_box', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True), size=4)),
                ('projection', models.CharField(max_length=30, validators=[cartoview.layers.validators.validate_projection])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid', models.BooleanField(default=True)),
                ('refresh_interval', models.DurationField(default=datetime.timedelta(days=7))),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='connections.Server')),
            ],
            options={
                'ordering': ('-name', '-created_at', '-updated_at'),
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('name', 'server')},
        ),
    ]
