# Generated by Django 2.1.3 on 2019-03-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='refresh_interval',
        ),
    ]
