# Generated by Django 2.2 on 2019-04-22 20:01

import cartoview.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='extra',
            field=cartoview.fields.DictField(),
        ),
    ]
