# Generated by Django 2.2 on 2019-05-22 13:43

import cartoview.fields
import cartoview.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0002_layer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='attribution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layer',
            name='tile_size',
            field=cartoview.fields.ListField(default=[256, 256], validators=[cartoview.validators.ListValidator(max_length=2, min_length=2)]),
        ),
        migrations.AddField(
            model_name='layer',
            name='urls',
            field=cartoview.fields.ListField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='wrap_x',
            field=models.BooleanField(default=True, help_text='Whether to wrap the world horizontally.'),
        ),
    ]
