# Generated by Django 2.1.3 on 2019-03-14 05:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0002_remove_layer_refresh_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), default=[], size=4),
        ),
    ]
