# Generated by Django 2.1.3 on 2019-03-15 17:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_layer_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), default=list, size=4),
        ),
    ]
