# Generated by Django 2.1.3 on 2019-02-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20190218_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appstore',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='apptype',
            options={'ordering': ['-name']},
        ),
    ]
