# Generated by Django 2.2 on 2019-04-23 10:00

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=200, null=True)),
                ('date_installed', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Installed')),
                ('single_instance', models.BooleanField(default=False)),
                ('status', models.CharField(default='Alpha', max_length=100)),
                ('app_img_url', models.TextField(blank=True, max_length=1000, null=True)),
                ('version', models.CharField(max_length=10)),
                ('order', models.IntegerField(default=0, unique=True)),
                ('default_config', jsonfield.fields.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
                'permissions': (('install_app', 'Install App'), ('uninstall_app', 'Uninstall App'), ('change_state', 'Change App State (active, suspend)')),
            },
        ),
    ]
