# Generated by Django 2.1.3 on 2019-02-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0002_auto_20190221_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='apps', to='app_manager.AppType'),
        ),
    ]
