# Generated by Django 2.2 on 2019-04-10 14:23

import cartoview.layers.validators
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_resource', '0002_basemodel_thumbnail'),
        ('app_manager', '0003_appinstance_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_resource.BaseModel')),
                ('name', models.CharField(default='No Name Provided', max_length=255)),
                ('extent', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True), size=4)),
                ('projection', models.CharField(max_length=30, validators=[cartoview.layers.validators.validate_projection])),
            ],
            bases=('base_resource.basemodel',),
        ),
        migrations.AddField(
            model_name='appinstance',
            name='bookmarks',
            field=models.ManyToManyField(to='app_manager.Bookmark'),
        ),
    ]
