# Generated by Django 2.1.3 on 2019-03-11 10:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0004_auto_20190311_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinstance',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
