# Generated by Django 2.2 on 2019-04-10 14:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0005_bookmark_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='extent',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), size=4),
        ),
    ]
