# Generated by Django 2.2 on 2019-04-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0006_auto_20190410_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinstance',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, to='app_manager.Bookmark'),
        ),
    ]
