# Generated by Django 2.2.12 on 2020-06-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0010_auto_20181118_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appinstance',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='appinstance',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='app',
            name='date_installed',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Installed'),
        ),
        migrations.AlterField(
            model_name='app',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_manager.AppStore'),
        ),
        migrations.AlterField(
            model_name='appstore',
            name='url',
            field=models.URLField(verbose_name='App Store URL'),
        ),
    ]
