# Generated by Django 2.2.12 on 2021-01-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0011_auto_20200623_1741'),
        ('app_manager', '0011_auto_20201021_2012'),
    ]

    operations = [
    ]
